stages:
  # - build
  # - test
  - x

# build-job:
#   stage: build
#   image: gradle:jdk21
#   tags:
#     - hva
#   script: ./gradlew build -x test

# test-job:
#   stage: test
#   image: gradle:jdk21
#   tags:
#     - hva
#   script: ./gradlew --build-cache test

x_job:
  image: docker:latest
  stage: x
  tags:
    - hva
  variables:
    PORT: 2222
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 $SSH_PRIVATE_KEY
  script: ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $SSH_USERNAME@$SSH_HOST
