stages:
  # - build
  # - test
  - pull_app

# build-job:
#   stage: build
#   image: gradle:jdk21
#   tags:
#     - hva
#   script: ./gradlew build -x test

# test-job:
#   stage: test
#   image: gradle:jdk21
#   tags:
#     - hva
#   script: ./gradlew --build-cache test

pull_app_job:
  stage: pull_app
  tags:
    - hva
  variables:
    PORT: 2222
  before_script: chmod 400 $SSH_KEY
  script: 
    - ssh -o StrictHostKeyChecking=no -i <(echo $SSH_KEY | base64 -d) $SSH_USERNAME@$SSH_HOST -p $PORT "
      echo Hello World!
      "